### ISSUE TITLE
how to create the database table for example/users?

### ISSUE THREAD

**Issue by yurenchen000** [caoym/phpboot#16]
```
> POST /apis/users/ HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: xxxx.com
> Accept: */*
> Cookie:token=12345
> Content-Length: 41
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 200 OK
< Server: nginx/1.4.6 (Ubuntu)
< Date: Wed, 17 Aug 2016 18:09:33 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/5.5.9-1ubuntu4.19
< 
<br />
<b>Fatal error</b>:  Uncaught exception 'ReflectionException' with message 'Cannot determine default value for internal functions' in ~/phprs/lib/phprs/util/IoCFactory.php:287
Stack trace:
#0 ~/phprs/lib/phprs/util/IoCFactory.php(287): ReflectionParameter-&gt;getDefaultValue()
#1 ~/phprs/lib/phprs/util/IoCFactory.php(138): phprs\util\IoCFactory-&gt;buildConstructArgs(Object(ReflectionClass), Array)
#2 ~/phprs/lib/phprs/util/IoCFactory.php(300): phprs\util\IoCFactory-&gt;create('db')
#3 ~/phprs/lib/phprs/util/IoCFactory.php(400): phprs\util\IoCFactory-&gt;getProperty('@db')
#4 ~/phprs/lib/phprs/util/IoCFactory.php(167): phprs\util\IoCFactory-&gt;injectDependent(Object(ReflectionClass), Object(Users), Array, Array, Object(Closure))
#5 ~/phprs/lib/phprs/Container.php(112): phprs\util\IoCFactory-&gt;create('Users', NULL, NULL, Object(Closure))
#6 ~/phprs/lib/phprs/Invoker.php(145): phprs\Container-&gt;getImpl(Object(phprs\Request))
#7 ~/phprs/lib/phprs/Router.php(198): phprs in <b>~/phprs/lib/phprs/util/IoCFactory.php</b> on line <b>287</b><br />
* Connection #0 to host yurenchen.com left intact
* Closing connection #0
```

seems database  table need initial ?
(i use 1.2.2)

**Comment by caoym** [comment]
1. use 1.2.3, which fixed issue caoym/phprs-restful#14
2. "Users.php" is not a complete and workable example, "Orders" at README.md may be better.
