### ISSUE TITLE
找不到类的报错

### ISSUE THREAD

**Issue by jurlin** [caoym/phpboot#24]
刚配置项目的时候出了个找不到类报错，不知道什么原因，然后自己在中间加了个引用类文件好了。

框架很好用，很期待！

**Comment by nirvana72** [comment]
我也是这个问题，你在中间加了个引用类文件是什么意思

**Comment by wuyougan** [comment]
类似的错误，不知道怎么处理

```
2020/04/14 14:05:52 [error] 195#195: *37 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Class App\Controllers\RequestAd does not exist in /var/www/localhost/htdocs/vendor/caoym/phpboot/src/Annotation/ContainerBuilder.php:42
Stack trace:
#0 /var/www/localhost/htdocs/vendor/caoym/phpboot/src/Annotation/ContainerBuilder.php(42): ReflectionClass->__construct('App\\Controllers...')
#1 /var/www/localhost/htdocs/vendor/caoym/phpboot/src/Controller/ControllerContainerBuilder.php(62): PhpBoot\Annotation\ContainerBuilder->build('App\\Controllers...')
#2 /var/www/localhost/htdocs/vendor/caoym/phpboot/src/Application.php(153): PhpBoot\Controller\ControllerContainerBuilder->build('App\\Controllers...')
#3 /var/www/localhost/htdocs/vendor/caoym/phpboot/src/Application.php(213): PhpBoot\Application->loadRoutesFromClass('App\\Controllers...', Array)
#4 /var/www/localhost/htdocs/public/index.php(21): PhpBoot\Application->loadRoutesFromPath('/var/www/localh...', 'App\\Controllers')
#5 {main}
  thrown in /var/www/localhost/htdocs/vendor/caoym" while reading response header from upstream, client: 10.0.5.102, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.5.23:6000"
```
